openapi: 3.2.0
info:
  description: SORACOM SANDBOX API v1
  title: 'SORACOM SANDBOX API Sandbox: Order API'
  version: 20230923-005714
servers:
- url: https://api-sandbox.soracom.io/v1
tags:
- name: 'API Sandbox: Order'
paths:
  /sandbox/orders/ship:
    post:
      description: Changes the shipping status to 'shipped' and gets ready the subscribers included in the order.
      operationId: sandboxShipOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/sandboxShipOrderRequest'
        description: Shipping request
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Order does not exist.
      security:
      - api_key: []
        api_token: []
      summary: Ships the specified order
      tags:
      - 'API Sandbox: Order'
      x-soracom-cli:
      - sandbox orders ship
components:
  schemas:
    sandboxShipOrderRequest:
      properties:
        operatorId:
          type: string
        orderId:
          type: string
      required:
      - orderId
      - operatorId
      type: object
